### ISSUE TITLE
[task]: トップ画面のQRコードの上にテキストを追加する

### ISSUE THREAD

**Issue by mmiura-2351** [mmiura-2351/procon#76]
### 目的

QRコードを押すことで拡大できることがわかりずらい

### タスクリスト

+ [x] QRコードの上にテキストを追加する(自由入力欄参照)

### Doneの定義

タスクが全て完了する

### 自由入力欄

「QRコードをタップで拡大」という文字列を追加する

**Comment by yuppiy4110** [comment]
完了
