### ISSUE TITLE
[Bug]: アカウント情報変更画面名前の入力ができない

### ISSUE THREAD

**Issue by yuppiy4110** [mmiura-2351/procon#87]
### 概要

アカウント情報変更画面にて名前の入力欄二つのうち上にある入力欄の入力、削除ができない。
下の入力欄の内容が表示されるだけのboxになってしまっている。

### 再現手順

1.アカウント情報変更画面にアクセス
2.一番上の入力欄で入力、削除を試す

### 期待した動作

名前の入力、削除が可能

### 使用したブラウザ

Chrome

**Comment by mmiura-2351** [comment]
done
