### ISSUE TITLE
[task]: パスワード変更画面にてパスワード間違ってるときの文章の表示位置が...

### ISSUE THREAD

**Issue by yuppiy4110** [mmiura-2351/procon#95]
### 目的

パスワード間違ってます文の表示位置が気になるので修正したほうがいいかも
![スクリーンショット 2024-02-07 142143](https://github.com/mmiura-2351/procon/assets/114715259/035e9556-4cbe-46a5-98a6-730e5a9ad059)

### タスクリスト

+ [ ] task01
+ [ ] task02

### Doneの定義

修正できた場合

### 参考

アカウント情報変更画面にてアカウント情報変更が完了した場合の表示位置
![スクリーンショット 2024-02-07 140705](https://github.com/mmiura-2351/procon/assets/114715259/c640209b-aeb1-4760-9422-e3afe491146a)

**Comment by mmiura-2351** [comment]
owari
